name: proper_place
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+18

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.0
  google_maps_flutter: ^2.5.0
  google_fonts: ^6.0.0
  geolocator: ^9.0.0
  image_picker: ^1.0.4
  intl: ^0.19.0
  flutter_stripe: ^11.0.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/images/login_background.png
